#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# lint-staged refers to the lint-staged tool that is installed as a Node.js package
# lint-staged is a Node.js package that allows you to run linters on your staged files
# lint-staged reads its configuration from .lintstagedrc.json
npx lint-staged